### ISSUE TITLE
Suggestion: MrCrayfish-like open source mods

### ISSUE THREAD

**Issue by blryface** [CustardMC/suggestions#2]
We could do mods simmilar to what MrCrayfish does, but open source and for all major loaders, if possible.

**Comment by blryface** [comment]
dont you ❤️ love ❤️ accidentally doing ctrl enter

**Comment by TheKodeToad** [comment]
I thought MrCrayfish does make open source mods ?

**Comment by TheKodeToad** [comment]
https://github.com/MrCrayfish

**Comment by blryface** [comment]
oh, fabric then?
(I had checked before and didn't see his mods were open source?? Idk 🗿)
